# Generated by Django 5.2.10 on 2026-01-08 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="User's phone number in E.164 format (e.g., +573001234567)", max_length=20)),
                ('message_text', models.TextField(help_text='Content of the message')),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default='incoming', help_text='Whether message is from user (incoming) or bot (outgoing)', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the message was created')),
                ('twilio_sid', models.CharField(blank=True, help_text='Twilio message SID for tracking', max_length=100, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Time in seconds for Ollama to process (for outgoing messages)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if message failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['phone_number', '-timestamp'], name='chatbot_mes_phone_n_2e6e60_idx'), models.Index(fields=['direction', '-timestamp'], name='chatbot_mes_directi_628e82_idx')],
            },
        ),
    ]
