# Generated by Django 5.2.10 on 2026-01-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.CharField(help_text="User's phone number in E.164 format (e.g., +573001234567)", max_length=50),
        ),
    ]
